name: blocs
description: Reactive Programming - BLoC - Practical Use Cases

version: 1.0.0+1

environment:
  sdk: ">=2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.21.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
